.PHONY: help setup dev build test clean logs stop start restart up down migrate db-shell db-init db-create db-upgrade db-downgrade db-history db-current db-stamp test-server-http test-server-http-dev

# Port of an API already running in dev mode (make dev-server / z-run.sh),
# used by test-server-http-dev. Override: make test-server-http-dev PORT=8080
PORT ?= 444

help:
	@echo "Bot Factory - Development Commands"
	@echo "===================================="
	@echo ""
	@echo "Setup & Installation:"
	@echo "  make setup          Setup project (create .env, install dependencies)"
	@echo "  make install-deps   Install Python and Node dependencies"
	@echo ""
	@echo "Development:"
	@echo "  make dev            Start development servers (Docker Compose)"
	@echo "  make dev-client     Start only Angular dev server"
	@echo "  make dev-server     Start only Flask dev server"
	@echo "  make db-only        Start only Mysql"
	@echo "  make chromadb-only  Start only Chroma db"
	@echo ""
	@echo "Docker:"
	@echo "  make build          Build Docker images"
	@echo "  make up             Start all services with Docker Compose"
	@echo "  make db-only        Start only the MySQL container"
	@echo "  make chromadb-only  Start only the ChromaDB container"
	@echo "  make down           Stop all services"
	@echo "  make restart        Restart all services"
	@echo "  make logs           View Docker logs"
	@echo "  make logs-api       View API logs only"
	@echo "  make logs-db        View MySQL logs only"
	@echo "  make logs-chromadb  View ChromaDB logs only"
	@echo ""
	@echo "Testing:"
	@echo "  make test           Run all tests"
	@echo "  make test-server    Run backend tests"
	@echo "  make test-server-http  Run the HTTP regression suite (docker-compose + mock LLM)"
	@echo "  make test-server-http-dev PORT=444  Run it against an API already running in dev mode"
	@echo "  make test-client    Run frontend tests"
	@echo ""
	@echo "Database:"
	@echo "  make migrate        Run database migrations (inside Docker container)"
	@echo "  make db-shell       Connect to MySQL database shell"
	@echo "  make db-init        Create alembic/ folder if missing"
	@echo "  make db-create MSG=\"message\"  Create a new autogenerated migration"
	@echo "  make db-upgrade     Apply all pending migrations (local, via uv)"
	@echo "  make db-downgrade   Revert the last migration"
	@echo "  make db-history     Show migration history"
	@echo "  make db-current     Show current database revision"
	@echo "  make db-stamp REV=head  Mark database at a revision without running SQL"
	@echo ""
	@echo "Cleanup:"
	@echo "  make clean          Remove generated files and caches"
	@echo "  make clean-docker   Remove Docker containers and volumes"
	@echo ""

# Setup
setup: .env install-deps
	@echo "✓ Project setup complete!"
	@echo "Run 'make dev' to start development"

.env:
	@echo "Creating .env file from .env.example..."
	cp .env.example .env
	@echo "⚠️  Please update .env with your local configuration"

install-deps:
	@echo "Installing backend dependencies..."
	cd server && uv sync
	@echo "Installing frontend dependencies..."
	cd client && npm ci
	@echo "✓ Dependencies installed"

# Development
dev: up
	@echo "✓ All services running. Access:"
	@echo "  Frontend: http://localhost:4200"
	@echo "  API: http://localhost:4444"
	@echo "  Database: localhost:3306"

dev-client:
	@echo "Starting Angular development server..."
	cd client && npm start

dev-server:
	@echo "Starting Flask development server..."
	cd server && bash z-run.sh

# Docker commands
build:
	@echo "Building Docker images..."
	docker-compose build

up:
	@echo "Starting Docker services..."
	docker-compose up -d
	@echo "✓ Services started. View logs with: make logs"

db-only:
	@echo "Starting MySQL container only..."
	docker-compose up -d db
	@echo "✓ MySQL running on localhost:3306"

chromadb-only:
	@echo "Starting ChromaDB container only..."
	docker-compose up -d chromadb
	@echo "✓ ChromaDB running on localhost:8000"

down:
	@echo "Stopping Docker services..."
	docker-compose down

stop:
	@echo "Stopping Docker services..."
	docker-compose stop

start:
	@echo "Starting Docker services..."
	docker-compose start

restart:
	@echo "Restarting Docker services..."
	docker-compose restart

logs:
	docker-compose logs -f

logs-api:
	docker-compose logs -f api

logs-db:
	docker-compose logs -f db

logs-chromadb:
	docker-compose logs -f chromadb

logs-web:
	docker-compose logs -f web

# Testing
test: test-server test-client
	@echo "✓ All tests completed"

test-server:
	@echo "Running backend tests..."
	cd server && uv run --extra test pytest test/ -v

test-server-single:
	@echo "Usage: make test-server-single TEST=test/test_file.py::test_name"
ifdef TEST
	cd server && uv run --extra test pytest $(TEST) -v
endif

test-server-http:
	@echo "Starting stack with mock LLM for the HTTP regression suite..."
	docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d --build db chromadb mock-llm api
	@echo "Running tests in a container on the compose network (reaches api/db by service name, no host networking involved)..."
	docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm test-runner
	@echo "✓ HTTP regression suite complete (stack left running; 'make down' to stop)"
	@echo "  Point a future FastAPI server instead: TEST_API_BASE_URL=http://api:<port>/api make test-server-http"

test-server-http-dev:
	@echo "Running HTTP regression suite against an API already running in dev mode on port $(PORT)..."
	@echo "(override with: make test-server-http-dev PORT=<port>)"
	@echo "Note: a manually-started dev server (z-run.sh) has no MISTRAL_BASE_URL set, so"
	@echo "test_rag.py will call the real Mistral API unless you export MISTRAL_BASE_URL"
	@echo "yourself before starting it."
	docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d db chromadb mock-llm
	@TARGET_HOST=""; \
	for candidate in $$(hostname) host.docker.internal; do \
		echo "Trying to reach the dev server via $$candidate:$(PORT)..."; \
		if docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm --no-deps test-runner \
			curl -sf http://$$candidate:$(PORT)/api/health > /dev/null 2>&1; then \
			TARGET_HOST=$$candidate; \
			break; \
		fi; \
	done; \
	if [ -z "$$TARGET_HOST" ]; then \
		echo "Could not reach port $(PORT) via this shell's own container ($$(hostname)) or"; \
		echo "host.docker.internal (the real host machine). If the dev server runs somewhere"; \
		echo "else reachable, point at it directly instead:"; \
		echo "  TEST_API_BASE_URL=http://<host>:$(PORT)/api make test-server-http-dev"; \
		exit 1; \
	fi; \
	echo "Reaching dev server via $$TARGET_HOST:$(PORT)"; \
	TEST_API_BASE_URL="http://$$TARGET_HOST:$(PORT)/api" \
	docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm --no-deps test-runner

test-client:
	@echo "Running frontend tests..."
	cd client && npm test -- --watch=false --browsers=ChromeHeadless

test-client-watch:
	@echo "Running frontend tests in watch mode..."
	cd client && npm test

# Database
migrate:
	@echo "Running database migrations..."
	docker-compose exec -w /app/db api alembic upgrade head
	@echo "✓ Migrations completed"

db-shell:
	@echo "Connecting to MySQL database..."
	docker-compose exec db mysql -u $${MYSQL_USER:-botcraft_user} -p$${MYSQL_PASSWORD:-123456789} $${MYSQL_DATABASE:-botcraft}

# Alembic migrations, run locally via uv (DATABASE_URL loaded from server/.env).
# Requires a reachable MySQL (e.g. `make db-only` or a local instance) — no
# Docker container exec needed since the DB port is published to the host.
db-init:
	@bash server/db/bootstrap_alembic.sh

db-create:
ifndef MSG
	$(error Usage: make db-create MSG="Description of the migration")
endif
	@echo "Creating new migration: $(MSG)"
	cd server/db && set -a && . ../.env && set +a && uv run alembic revision --autogenerate -m "$(MSG)"
	@echo "✓ Migration created — review the generated file in server/db/alembic/versions/"

db-upgrade:
	@echo "Applying pending migrations..."
	cd server/db && set -a && . ../.env && set +a && uv run alembic upgrade head
	@echo "✓ Migrations applied"

db-downgrade:
	@echo "Reverting last migration..."
	cd server/db && set -a && . ../.env && set +a && uv run alembic downgrade -1
	@echo "✓ Migration reverted"

db-history:
	@echo "Migration history:"
	cd server/db && set -a && . ../.env && set +a && uv run alembic history

db-current:
	@echo "Current database revision:"
	cd server/db && set -a && . ../.env && set +a && uv run alembic current

db-stamp:
ifndef REV
	$(error Usage: make db-stamp REV=<revision|head>)
endif
	@echo "Stamping database at revision: $(REV)"
	cd server/db && set -a && . ../.env && set +a && uv run alembic stamp $(REV)
	@echo "✓ Database stamped"

# Cleanup
clean:
	@echo "Cleaning up generated files..."
	find . -type f -name "*.pyc" -delete
	find . -type d -name "__pycache__" -exec rm -r {} + 2>/dev/null || true
	find . -type d -name ".angular" -exec rm -r {} + 2>/dev/null || true
	find . -type d -name "node_modules" -exec rm -r {} + 2>/dev/null || true
	find . -type d -name "dist" -exec rm -r {} + 2>/dev/null || true
	@echo "✓ Cleanup completed"

clean-docker:
	@echo "Removing Docker containers and volumes..."
	docker-compose down -v
	@echo "✓ Docker resources cleaned"

clean-all: clean clean-docker
	@echo "Removing virtual environments..."
	rm -rf server/.venv
	@echo "✓ Complete cleanup finished"

# Linting and formatting (optional, for future use)
lint-server:
	@echo "Linting Python code..."
	cd server && uv run --extra dev flake8 ai_server/

lint-client:
	@echo "Linting TypeScript code..."
	cd client && npm run lint

format-server:
	@echo "Formatting Python code..."
	cd server && uv run --extra dev black ai_server/

format-client:
	@echo "Formatting TypeScript code..."
	cd client && npx prettier --write src/
