"""first migration

Revision ID: 31689b35e242
Revises: 
Create Date: 2026-08-05 08:47:25.489249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31689b35e242'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('mail', sa.String(length=128), nullable=False),
    sa.Column('roles', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('selected_bot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['selected_bot_id'], ['bot.id'], name='fk_user_account_selected_bot_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_guest_id', sa.Integer(), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_avatar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Integer(), nullable=False),
    sa.Column('body_color', sa.Integer(), nullable=False),
    sa.Column('hat', sa.Integer(), nullable=False),
    sa.Column('hat_color', sa.Integer(), nullable=False),
    sa.Column('eyes', sa.Integer(), nullable=False),
    sa.Column('eyes_color', sa.Integer(), nullable=False),
    sa.Column('mouth', sa.Integer(), nullable=False),
    sa.Column('mouth_color', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_guest_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('bot_name', sa.String(length=64), nullable=False),
    sa.Column('bot_type', sa.String(length=128), nullable=True),
    sa.Column('interlocutor_type', sa.String(length=128), nullable=True),
    sa.Column('interlocutor_identity', sa.String(length=128), nullable=True),
    sa.Column('main_personality_trait_1', sa.String(length=128), nullable=True),
    sa.Column('main_personality_trait_2', sa.String(length=128), nullable=True),
    sa.Column('main_personality_trait_3', sa.String(length=128), nullable=True),
    sa.Column('used_sources', sa.String(length=128), nullable=True),
    sa.Column('context_type', sa.String(length=128), nullable=True),
    sa.Column('answer_style', sa.String(length=128), nullable=True),
    sa.Column('answer_length', sa.String(length=128), nullable=True),
    sa.Column('goal', sa.String(length=128), nullable=True),
    sa.Column('behaviour_when_ignore', sa.String(length=128), nullable=True),
    sa.Column('behaviour_with_language', sa.String(length=128), nullable=True),
    sa.Column('localisation', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iframe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('allowed_origins', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=54), nullable=False),
    sa.Column('date', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=False),
    sa.Column('knowledge_dad_id', sa.String(length=64), nullable=False),
    sa.Column('children_ref_id', sa.String(length=64), nullable=False),
    sa.Column('indice', sa.Integer(), nullable=False),
    sa.Column('pdf_file', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=4096), nullable=False),
    sa.Column('time', sa.String(length=64), nullable=False),
    sa.Column('hide', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('knowledge')
    op.drop_table('iframe')
    op.drop_table('bot_parameters')
    op.drop_table('bot_guest_assignment')
    op.drop_table('bot_avatar')
    op.drop_table('token_usage')
    op.drop_table('session')
    op.drop_table('bot')
    op.drop_table('user_account')
    # ### end Alembic commands ###
