import pytest

from src.services.passwords import hash_password, needs_rehash, verify_password

# Generated by Werkzeug 3.0.1's generate_password_hash("s3cret-pass"), the
# scheme every account created before Argon2 was introduced still has.
WERKZEUG_HASHES = [
    "scrypt:32768:8:1$rns4GlbR9UJQ6HcY$5be599d57c42ae04b8f45dde0e4c2544d8db86f59060e767b4e62ed8a102c245a0967f404e27944cadad93db6bb0c48e5eb2b27d5e768b49bb8be644988ddc0c",
    "pbkdf2:sha256:1000$S7ftnye2sGVnJ6dY$b922ad6402b77872c7451211911de9537524fc92641bbe9f46af4f298b557b03",
]


def test_argon2_round_trip():
    password_hash = hash_password("s3cret-pass")
    assert password_hash.startswith("$argon2id$")
    assert verify_password(password_hash, "s3cret-pass")
    assert not verify_password(password_hash, "wrong")
    assert not needs_rehash(password_hash)


@pytest.mark.parametrize("password_hash", WERKZEUG_HASHES)
def test_werkzeug_hashes_still_verify_and_need_rehash(password_hash):
    assert verify_password(password_hash, "s3cret-pass")
    assert not verify_password(password_hash, "wrong")
    assert needs_rehash(password_hash)


@pytest.mark.parametrize("password_hash", ["", "garbage", "scrypt:x$y$z", "pbkdf2:md5$a$b"])
def test_malformed_hash_never_verifies(password_hash):
    assert not verify_password(password_hash, "anything")
